### ISSUE TITLE
My password contains a column.

### ISSUE THREAD

**Issue by JulienPalard** [metaodi/osmapi#105]
Hi! 

Thanks for osmapi!

I'm having a small issue though, but easy to fix: while reading the password from the password file, using `line = line.strip().split(":", 1)` instead of `line = line.strip().split(":")` would allow my password to read correctly. As my password contains a column, it currently split in three parts, and the last one is discarded.

Bests.

**Comment by metaodi** [comment]
The fix is part of release 1.3.0
