### ISSUE TITLE
Closing the requests.session

### ISSUE THREAD

**Issue by JulienPalard** [metaodi/osmapi#107]
OsmApi should provide a `.close()` method to close the underlying `_session` object, to avoid `ResourceWarning: unclosed <ssl.SSLSocket` warnings.

It could also provide a `__enter__` and a `__exit__`, to implicitly call the close at exit.

**Comment by metaodi** [comment]
Related to #89

**Comment by metaodi** [comment]
The fix is part of release 1.3.0
