### ISSUE TITLE
Consider more specific exceptions than osmapi.OsmApi.ApiError

### ISSUE THREAD

**Issue by matkoniecz** [metaodi/osmapi#115]
> osmapi.OsmApi.ApiError: Request failed: 409 - Conflict - b'The changeset 111530865 was closed at 2021-09-22 09:42:47 UTC'

I would like to catch just "adding to closed changeset" errors  and it seems that it will require error prone parsing of strings. Is there a better way to do this?

**Comment by matkoniecz** [comment]
Wait, it seems that it should be covered by #38

**Comment by metaodi** [comment]
@matkoniecz so is this resolved or do you suggest other exceptions?

**Comment by matkoniecz** [comment]
I am using osmapi 1.3.0 that includes #38 and I get exceptions such as `osmapi.OsmApi.ApiError: Request failed: 409 - Conflict - b'The changeset 111530865 was closed at 2021-09-22 09:42:47 UTC'`

So it is still needed. While #38 added `osmapi.NoChangesetOpenError` it seems to be used when there is no changeset open at all, not when there is attempt to add to an already closed changeset.

So yes, I am proposing  `osmapi.ChangesetAlreadyClosedError` (maybe make it subtype of `osmapi.OsmApi`? as I understand it would preserve backward compatibility)

**Comment by metaodi** [comment]
Ok got it, thanks for reporting this issue.
