### ISSUE TITLE
Don't raise XmlResponseInvalidError when using NodeRelations

### ISSUE THREAD

**Issue by FisherTsai** [metaodi/osmapi#117]
Function NodeRelations raises XmlResponseInvalidError when the target element isn't used in any relations. In this situation, OSM API do return an valid XML with an empty \<osm\> element (Check the definition [here](https://wiki.openstreetmap.org/wiki/API_v0.6#Relations_for_element:_GET_.2Fapi.2F0.6.2F.5Bnode.7Cway.7Crelation.5D.2F.23id.2Frelations)). I don't think raising XmlResponseInvalidError in this situation is a proper way to go. It might be better to return an empty list, just like the behavior in osmapi v1.0.0.

Consider to make a change for this? For this function, improving the error handling to deal with this or just rolling back to v1.0.0?

Notes that function NodeWays has the same issue.

**Comment by metaodi** [comment]
@FisherTsai thanks for reporting this issue. I'll look into it.
