### ISSUE TITLE
more specific exception than osmapi.OsmApi.ApiError for already closed note

### ISSUE THREAD

**Issue by matkoniecz** [metaodi/osmapi#135]
`osmapi.errors.ApiError: Request failed: 409 - Conflict - b'The note 3158344 was closed at 2022-04-29 20:57:20 UTC'`

`osmapi.NoteAlreadyClosedError` would be nice

basically the same case as #115

**Comment by matkoniecz** [comment]
Also

> osmapi.OsmApi.ApiError: Request failed: 404 - Not Found - b''

would be nice to have as a more specific error

**Comment by matkoniecz** [comment]
BTW, thanks for this library! I recently used it to close several hundred spam notes created by a vandal (that is why I discovered issue reported here)

**Comment by metaodi** [comment]
Thanks, I hope I'll get to it soon.
