### ISSUE TITLE
Can not create a dev account. 

### ISSUE THREAD

**Issue by masudr4n4** [metaodi/osmapi#136]
![image](https://user-images.githubusercontent.com/34313493/183387796-aec3c023-d20f-4201-a706-f429e14a2507.png)

**Comment by metaodi** [comment]
It seems to be down. I don't know anything about it, but I [asked via Twitter](https://twitter.com/odi/status/1556579703208775680), let's hope it come back soon.

**Comment by metaodi** [comment]
The [OSM tech team answered](https://twitter.com/OSM_Tech/status/1556587556212539392) that they have problems with the dev server and it's "unlikely to be stable until late this week".

**Comment by metaodi** [comment]
Closing this for now.
