### ISSUE TITLE
Warn about missing user agent

### ISSUE THREAD

**Issue by dpriskorn** [metaodi/osmapi#151]
OSMF requires a user-agent to be supplied:

Technical Usage Requirements

    Valid User-Agent identifying application and version. Faking another app’s User-Agent WILL get you blocked.

https://operations.osmfoundation.org/policies/api/

**Comment by metaodi** [comment]
The user-agent is set to the value provided to the `created_by` parameter, which defaults to `osmapi/{__version__}` (e.g. osmapi/4.0.0)

**Comment by dpriskorn** [comment]
Yes, I know, but like WikibaseIntegrator osmapi should warn that it should be set by the user IMO.
The foundation has no idea who uses your module.

**Comment by metaodi** [comment]
I don't understand. It's supposed to be the software that is used to edit OSM (like iD or Patlatch). The one who uses the software is the user/author of the changeset.

Of course, if someone creates their own software that uses osmapi, they should provide the `created_by` parameter. But I don't think this should be enforced.

**Comment by metaodi** [comment]
Since osmapi always sets a user agent, I consider this ticket as resolved.
