### ISSUE TITLE
Update examples in readme to set a user-agent 

### ISSUE THREAD

**Issue by dpriskorn** [metaodi/osmapi#152]
See https://github.com/metaodi/osmapi/issues/151

**Comment by matkoniecz** [comment]
note that it was rejected in https://github.com/metaodi/osmapi/issues/151#issuecomment-2009348426

(though setting user agent specific to a given script seems to be a good idea to me)

**Comment by metaodi** [comment]
I added an example to the README how to set the "user-agent": https://github.com/metaodi/osmapi/blob/develop/README.md#user-agent--credit-for-application
