### ISSUE TITLE
Warn before note creation 

### ISSUE THREAD

**Issue by dpriskorn** [metaodi/osmapi#153]
The wini states "Don't create automated notes. Notes should be a human-to-human communication. Also avoid noting lots of data bugs which are already reported by automated Quality Assurance tools."

osmapi should warn the user before creating notes.

You could also link to https://wiki.openstreetmap.org/wiki/Notes and maproulette.

**Comment by metaodi** [comment]
osmapi is a wrapper for the OSM API (i.e. to be used by other software developers to communicate with OSM). A typical use case might be an app that has a user interface to create such notes.

So there is not really a way "to warn the user" other than the documentation here. And there are a ready plenty of warnings/notices how to use/not use this library.

How would you improve the docs and/or the warnings to other devs?

**Comment by matkoniecz** [comment]
There is already https://github.com/metaodi/osmapi?tab=readme-ov-file#note-about-imports--automated-edits

maybe make it subsection of https://github.com/metaodi/osmapi?tab=readme-ov-file#write-to-openstreetmap to make it more visible?

(see for example https://github.com/matkoniecz/osm_bot_abstraction_layer where I went quite extreme on userproofing the documentation)

@dpriskorn Note that osmapi is not used only in automated bot editing, I create notes using scripts but manually and on verifying each case (see say https://www.openstreetmap.org/note/3968258 or https://www.openstreetmap.org/note/3862857 or https://www.openstreetmap.org/note/3428677 )

**Comment by matkoniecz** [comment]
@metaodi I think this issue can be closed given no response
