### ISSUE TITLE
more specific exception than osmapi.OsmApi.ApiError for already closed changeset

### ISSUE THREAD

**Issue by matkoniecz** [metaodi/osmapi#177]
`osmapi.ChangesetAlreadyClosedError` or similar would be nice

see say https://github.com/metaodi/osmapi/issues/135

current workaround is too use 

`if "Request failed: 409 - Conflict" in str(e) and "was closed at " in str(e):`

which is kind of ugly hack (which may fail in some cases, I guess).

**Comment by metaodi** [comment]
This exists already, it's called `ChangesetClosedApiError` and is raised when an ApiError occurs and the status code is 409.

**Comment by matkoniecz** [comment]
weird, it listed in https://github.com/metaodi/osmapi/blob/develop/CHANGELOG.md#200---2021-11-22 - 2.0.0 version released in 2021.

Maybe I caught `osmapi.OsmApi.ApiError` and it is catching ChangesetClosedApiError but I should rather catch specifically ChangesetClosedApiError in earlier `except` clause?

**Comment by metaodi** [comment]
Yes that's exectly it, you must catch more specific exceptions first.
