### ISSUE TITLE
NodeHistory incomplete result

### ISSUE THREAD

**Issue by m-aliakbarian** [metaodi/osmapi#40]
I am trying to fetch history of nodes, for the ones who have a version more than 10 I won't get a full history but rather from version 10.

code:
node_history = MyApi.NodeHistory(each_id)
print ((node_history[len(node_history)]['timestamp'])-(node_history[1]['timestamp'])).days

example case: node with osm id of 288340413. So instead of getting a dict with length of 11 I get a dict with length of 2.

**Comment by metaodi** [comment]
This is actually the response from the API: http://api.openstreetmap.org/api/0.6/node/288340413/history

i.e. it only returns those two versions, prior versions seem not to exists (e.g. http://api.openstreetmap.org/api/0.6/node/288340413/2 returns nothing).

For other nodes with more than 10 nodes this is different: http://api.openstreetmap.org/api/0.6/node/116066941/history returns 12 versions, each can be accessed individually by the API (http://api.openstreetmap.org/api/0.6/node/116066941/1, http://api.openstreetmap.org/api/0.6/node/116066941/2, http://api.openstreetmap.org/api/0.6/node/116066941/3, ...)

The problems seems to be the specific node 288340413, that only has two versions. I don't know why it doesn't start from 1 or what happened there, but this is how it appears.

**Comment by m-aliakbarian** [comment]
Thanks for your comprehensive answer and sorry for my generalization of the case. Checking the provided links I agree about your points.
And also thanks for the API in general.
