### ISSUE TITLE
Documentation website does not work - hosting provider has ceased operation

### ISSUE THREAD

**Issue by mbdevpl** [metaodi/osmapi#49]
Currently (1st Jan 2016) the page http://osmapi.divshot.io/ displays the following message:

> Site Unavailable
> 
> Divshot, the hosting provider for this website, has ceased operation as of December 22, 2015. Divshot technology now powers Firebase Hosting.
> 
> If this is your website, please update your DNS to point to a new hosting provider!

Is there any other page with documentation?

**Comment by austinhartzheim** [comment]
@mbdevpl You can generate the documentation yourself with the `pdoc` tool, as mentioned in the README. This is the same as the documentation that was hosted at that address.

On my system, I needed to install osmapi for Python 2 for `pdoc` to find it.

**Comment by metaodi** [comment]
@mbdevpl @austinhartzheim I'll take care of an alternative.

**Comment by metaodi** [comment]
You can find the documentation here: http://osmapi.metaodi.ch/

**Comment by mbdevpl** [comment]
Thank you very much!

-----Original Message-----
