### ISSUE TITLE
Add ability to send messages?

### ISSUE THREAD

**Issue by jschleuss** [metaodi/osmapi#59]
I am constantly reaching out to local users with the same message by copy/pasting the markdown into page after page. Would be handy to be able to send a message programmatically to an entire group.

**Comment by metaodi** [comment]
@jschleuss do you know where/if there is an API for messaging in OSM?

**Comment by matkoniecz** [comment]
It seems that all can be done is to check unread message count - see http://wiki.openstreetmap.org/wiki/Web_front_end#User_messaging and https://josm.openstreetmap.de/ticket/9234

**Comment by jschleuss** [comment]
@metaodi god, I'm sorry I missed that mention so many months back.

I ended up writing a python script that slowly sent messages. It wasn't preferable, but it got the job done (over a few hours).

**Comment by metaodi** [comment]
@jschleuss no problem. I'm closing this for now as there seems to be no API endpoint for messaging.
