### ISSUE TITLE
Error installing on clean virtualenv

### ISSUE THREAD

**Issue by Xevib** [metaodi/osmapi#67]
When I install osmapi on a clean virtualenv with python 2.7.11 I get this:
Collecting osmapi
  Downloading osmapi-0.7.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_d5sLy/osmapi/setup.py", line 6, in <module>
        version = __import__('osmapi').__version__
      File "osmapi/__init__.py", line 5, in <module>
        from .OsmApi import *  # noqa
      File "osmapi/OsmApi.py", line 35, in <module>
        import requests
    ImportError: No module named requests

**Comment by metaodi** [comment]
Do you use 'pip install osmapi' to install it? requests is a dependency that pip should resolve, it's defined in our requirements.txt file.

**Comment by Xevib** [comment]
Yes, I used pip install osmapi

**Comment by metaodi** [comment]
I could perfectly reproduce your issue. I just read https://caremad.io/posts/2013/07/setup-vs-requirement/ and it seems the correct way of defining a dependency in a library is to add it as `install_requires` in setup.py. So hopefully my PR fixes this issue.

**Comment by metaodi** [comment]
@Xevib I could finally fix the installation problem and osmapi 0.8.1 can be installed in a clean virtualenv without a problem. I added a test to my build script to make sure these kind of problems are detected earlier next time. Thanks you very much for reporting this issue.
