### ISSUE TITLE
Add the changeset logic as context manager

### ISSUE THREAD

**Issue by metaodi** [metaodi/osmapi#89]
I imagine to open a changeset using the *with* keyword, doing some operations and then it is closed automatically.
A similar logic is already there with the destructor, but this is not guaranteed to work and less explicit.

**Comment by metaodi** [comment]
See https://github.com/metaodi/osmapi/issues/39#issuecomment-336038965 for details

**Comment by diegocrzt** [comment]
Is somebody working on this? or is there any update about this?

**Comment by metaodi** [comment]
@diegocrzt I started to work on this :)
