### ISSUE TITLE
unhelpful crash message

### ISSUE THREAD

**Issue by matkoniecz** [metaodi/osmapi#90]
I guess that I provided wrong data but

```
  File "/usr/local/lib/python3.5/dist-packages/osmapi/OsmApi.py", line 343, in NodeGet
    data = data.getElementsByTagName("node")[0]
IndexError: list index out of range
```

is unhelpful in diagnosing what went wrong.

Maybe throwing a more readable exception explaining what is wrong would be a better idea?

**Comment by metaodi** [comment]
I totally agree. What node did you try to get (I'm asking to write a meaningful test for it)? I guess the OSM API returned an emtpy result.

**Comment by matkoniecz** [comment]
Unfortunately I have no idea, what worse running the same code again resulted in lack of crash (probably it was a network error).

**Comment by metaodi** [comment]
In #91 I introduced a new error called `XmlResponseInvalidError` which is raised, whenever the response from the OpenStreetMap API is invalid. You can either catch it in your application or at least get a better error message, should it ever occur (again).

**Comment by matkoniecz** [comment]
Thanks!
