### ISSUE TITLE
print() is a function in Python 3

### ISSUE THREAD

**Issue by cclauss** [metaodi/osmapi#95]
The third line of code on https://wiki.openstreetmap.org/wiki/Osmapi is a syntax error.

**Comment by metaodi** [comment]
@cclauss the code on this wiki page is obviously Python 2. I think it's time to update all examples with Python 3 code. Could you help with this?

**Comment by metaodi** [comment]
Note to myself: this includes the examples in the README of this repo.

**Comment by metaodi** [comment]
Fixed with #96
